version: 2.1

executors:
  my-exec-env:
    docker:
      - image: circleci/node:13.8.0

jobs:
  build:
    executor: my-exec-env
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - save_cache:
          key: my-dependencies
          paths:
            - ./node_modules
  
  test:
    executor: my-exec-env
    steps:
      - checkout
      - restore_cache:
          keys:
            - my-dependencies
      - run: npm install
      - run: npm run test
  
  analyse:
    executor: my-exec-env
    steps:
      - checkout
       - run: npm audit fix
      - run:
          name: Tell of vulnerability
          command: echo Vulnerability Found
          when: on_fail

workflows:
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test